apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: persistent-server
spec:
  selector:
    app: nginx-persistent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
